### ISSUE TITLE
Interest in the Full Stack Developer position

### ISSUE THREAD

**Issue by Pedrolopesh** [london-bridge/hiring#1]
I am writing to express my interest in the Full Stack Developer position at London Bridge. With my extensive experience in full-stack development, I believe I would be an excellent fit for this role.

As you have specified in the job description, I possess a wide range of skills, including NestJS, GraphQL, NextJS, React, and TypeScript. Moreover, I am proficient in OWASP, microservices, and Monorepo, which are also mentioned in your requirements.

I have over five years of experience in the technology market, with a focus on web development, and I have worked with several frameworks such as Vue js, React js, and Next js. In my previous positions, I have led teams of developers to create new features and customizations using React js, Typescript, and Node js.

Additionally, I have experience developing new components and functionalities for e-commerce stores using Node js for APIs and React in frontend.I am also proficient in several other technologies, including Docker, AWS, MongoDB, and MySQL

I am excited about the opportunity to contribute my skills and experience to the team at London Bridge. Thank you for considering my application.

Sincerely,
Pedro Lopes

**Comment by brunowego** [comment]
Hello @Pedrolopesh , thank you very much for your interest in being part of our time! At this moment, we have a full team, but we are growing and new opportunities will appear soon.
