### ISSUE TITLE
Mobile - hiring

### ISSUE THREAD

**Issue by CarlosTSIlva** [london-bridge/hiring#2]
[Linkedin](http://linkedin.com/in/carlos-t-silva/)
My name is Carlos and I am a software engineer with over 4 years of experience in programming, and 2 years specifically in Flutter. Since the beginning of my career, I have dedicated myself to learning and applying new technologies, always seeking to optimize and improve my skills.

My experience in programming has allowed me to develop efficient and innovative solutions for companies in various industries. In addition, my specialization in Flutter allows me to create high-performance mobile applications with good usability and scalability.

Technology:
- GIT
- Flutter/Dart
- Cloud functions/VPC/Google Cloud Platform
- Firebase Authentication/Firestore Database/Storage
- Redux, Bloc, Getx e Provider
- Injeção de dependencias: GetIt
- MVC, repositories, data sources 
- Responsibilities
- Web Services/APIs
• Persistencia de dados
• MVC e MVP
• clean architecture
• clean code
• unitary tests

## Code Sample URL #1

Currently the code I'm most proud of would be the deeplink because it was recent and was thought and architected in a legal way.

```
import 'package:flutter/material.dart';
import 'package:pd_mobile_flutter/routes/app_routes.dart';
import 'package:uni_links/uni_links.dart';

class DeepLink {
  Future<void> handleDeepLink(BuildContext context) {
    return getInitialLink().then((linkResult) {
      final link = Uri.parse(linkResult ?? '');
      switch (link.path) {
        case DeepLinkPath.updatePassword:
          final token = link.queryParameters['token'] ?? '';
          Navigator.pushNamed(context, AppRoutes.confirmNewPassword,
              arguments: token);
          break;
        default:
          Navigator.pushReplacementNamed(context, AppRoutes.login);
          return;
      }
    });
  }
}

class DeepLinkPath {
  static const String updatePassword = '/updatePassword';
}
```

**Comment by brunowego** [comment]
Hi @CarlosTSIlva, thanks for the interest. We are about to take the next step towards building our mobile app. I will get in touch with your linkedin so we can take the next steps.
